# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TFB_Tools3
                                 A QGIS plugin
 圖資操作處理工具
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-06-20
        copyright            : (C) 2019 by FCU-GIS
        email                : gis.tw
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# # noinspection PyPep8Naming
# def name():
#        return "TFB-Tools3"

# def description():
#        return "TFB-Tools v3.0_plugins"

# def version():
#        return "3.0"

# def qgisMinimumVersion():
#        return "3.4"

# def authorName():
#        return "Vincent"


def classFactory(iface):  # pylint: disable=invalid-name
    """Load TFB_Tools3 class from file TFB_Tools3.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .TFB_Tools3 import TFB_Tools3    
    return TFB_Tools3(iface)
    
    
    
