# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\vincentlu\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\TFB-Tools3\cadastre_dia.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastre_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(628, 409)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 601, 371))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(90, 10, 161, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 45, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 45, 161, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_3.setGeometry(QtCore.QRect(90, 80, 321, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(420, 80, 91, 25))
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(90, 110, 321, 181))
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listWidget.setObjectName("listWidget")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 300, 91, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(420, 100, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.listWidget_2 = QtWidgets.QListWidget(self.tab)
        self.listWidget_2.setEnabled(True)
        self.listWidget_2.setGeometry(QtCore.QRect(420, 150, 151, 111))
        self.listWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listWidget_2.setObjectName("listWidget_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(262, 300, 81, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(350, 300, 61, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(420, 270, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(90, 300, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 391, 131))
        self.groupBox.setObjectName("groupBox")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(90, 28, 111, 25))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(60, 90, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 60, 131, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 90, 131, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 90, 91, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(240, 50, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.checkBox.setFont(font)
        self.checkBox.setIconSize(QtCore.QSize(24, 24))
        self.checkBox.setObjectName("checkBox")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_2.setEnabled(True)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 361, 261))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_2.setEnabled(True)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 10, 341, 211))
        self.tableWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(True)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 341, 211))
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_3.setEnabled(True)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 10, 341, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_3.sizePolicy().hasHeightForWidth())
        self.tableWidget_3.setSizePolicy(sizePolicy)
        self.tableWidget_3.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableWidget_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(18)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(21)
        self.tableWidget_3.verticalHeader().setCascadingSectionResizes(True)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_4.setEnabled(True)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 10, 341, 211))
        self.tableWidget_4.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableWidget_4.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(1)
        self.tableWidget_4.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        self.tableWidget_4.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_4.verticalHeader().setCascadingSectionResizes(True)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 270, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_5.setGeometry(QtCore.QRect(380, 50, 121, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(380, 30, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_3, "")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(190, 380, 381, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "地籍查詢"))
        self.label_4.setText(_translate("Dialog", "縣市："))
        self.label_5.setText(_translate("Dialog", "鄉鎮："))
        self.label_6.setText(_translate("Dialog", "地段名稱："))
        self.label_7.setText(_translate("Dialog", "地號："))
        self.pushButton.setText(_translate("Dialog", "取得地號"))
        self.pushButton_4.setText(_translate("Dialog", "載入圖層"))
        self.label_8.setText(_translate("Dialog", "已選取地號：\n"
"請由左欄選取地號或自行輸入"))
        self.listWidget_2.setSortingEnabled(True)
        self.pushButton_5.setText(_translate("Dialog", "自行輸入"))
        self.label_11.setText(_translate("Dialog", "↑點擊欲刪除地號即可刪除"))
        self.label_12.setText(_translate("Dialog", "↑點擊欲加入地號即可加入"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "地段/地號"))
        self.groupBox.setTitle(_translate("Dialog", "輸入座標"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "TWD_97"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "WGS_84"))
        self.label.setText(_translate("Dialog", "坐標系統"))
        self.label_2.setText(_translate("Dialog", "X"))
        self.label_3.setText(_translate("Dialog", "Y"))
        self.lineEdit_2.setText(_translate("Dialog", "311791.151"))
        self.lineEdit_3.setText(_translate("Dialog", "2770590.391"))
        self.pushButton_3.setText(_translate("Dialog", "載入地籍圖"))
        self.checkBox.setText(_translate("Dialog", "圖面點選模式"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "坐標"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "段名"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "地號"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "登記日期"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "登記原因"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "面積"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "使用分區"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "使用地類別"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "公告地現值"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "公告地價"))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "縣市"))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "鄉鎮市區"))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "圖幅號"))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "地上建物建號數量"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "值"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Dialog", "土地標示部"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "段名"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "地號"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "登記日期"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "登記原因"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "登記原因發生日期"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "權利範圍類別"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "權利範圍分母"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "權利範圍分子"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "權狀年期"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "權狀字"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "權狀號"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "申報地價"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "值"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Dialog", "土地所有權部"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "段名"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "地號"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "他項權利登記次序"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "收件年期"))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "收件字"))
        item = self.tableWidget_3.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "收件號"))
        item = self.tableWidget_3.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "登記日期"))
        item = self.tableWidget_3.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "登記原因"))
        item = self.tableWidget_3.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "設定權利範圍類別"))
        item = self.tableWidget_3.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "設定權利範圍持分分母"))
        item = self.tableWidget_3.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "設定權利範圍持分分子"))
        item = self.tableWidget_3.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "設定權利範圍面積"))
        item = self.tableWidget_3.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "證明書字號"))
        item = self.tableWidget_3.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "債權權利範圍類別"))
        item = self.tableWidget_3.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "債權權利範圍持分分母"))
        item = self.tableWidget_3.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "債權權利範圍持分分子"))
        item = self.tableWidget_3.verticalHeaderItem(16)
        item.setText(_translate("Dialog", "權利種類"))
        item = self.tableWidget_3.verticalHeaderItem(17)
        item.setText(_translate("Dialog", "標的種類"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "值"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Dialog", "他項權利部"))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "段名"))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "地號"))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "收件年期"))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "收件字"))
        item = self.tableWidget_4.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "收件號"))
        item = self.tableWidget_4.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "登記日期"))
        item = self.tableWidget_4.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "登記原因"))
        item = self.tableWidget_4.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "建物總面積"))
        item = self.tableWidget_4.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "建物門牌"))
        item = self.tableWidget_4.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "主要用途"))
        item = self.tableWidget_4.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "主要建材"))
        item = self.tableWidget_4.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "建物層數"))
        item = self.tableWidget_4.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "建築完成日期"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "值"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("Dialog", "建物標示部"))
        self.pushButton_2.setText(_translate("Dialog", "複製表格"))
        self.label_10.setText(_translate("Dialog", "下拉切換地號資訊"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "公有土地資訊"))
        self.label_9.setText(_translate("Dialog", "* 本資料來源為內政部地政司，地中地圖形未處理，請查對使用 *"))


