# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TFB_Tools3DockWidget
                                 A QGIS plugin
 圖資操作處理工具
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-06-20
        git sha              : $Format:%H$
        copyright            : (C) 2019 by FCU-GIS
        email                : gis.tw
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt5 import QtGui, QtWidgets, uic
from PyQt5.QtCore import pyqtSignal

from .Ui_WMTS_dia import *
from .Ui_addWMTS_dia import *
from .Ui_csv2shp_dia import *
from .Ui_gpx2shp_dia import *
from .Ui_exportSHP_dia import *
from .Ui_editPOLY_dia import *
from .Ui_photogpx import *
from .Ui_impphotos import *
from .Ui_GPXrevise import *
from .Ui_wms_dia import *
# from .Ui_positioning_dia import *
from .Ui_positioning_dia import *
from .Ui_cadastre_dia import *
from .Ui_infor_dia import*
from .Ui_Ecological2shp_dia import*
from .Ui_imgpareCSV_dia import*

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'TFB_Tools3_dockwidget_base.ui'))


class TFB_Tools3DockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(TFB_Tools3DockWidget, self).__init__(parent)
        QtWidgets.QDialog.__init__(self)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        # self.setGeometry(0, 0, 3572, 3524)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()

class Ui_WMTS(QtWidgets.QDialog, Ui_WMTS_Dialog):
    def __init__(self, iface):
        QtWidgets.QDialog.__init__(self)
        self.iface = iface
        self.setupUi(self)

class Ui_addWMTS(QtWidgets.QDialog, Ui_addWMTS_Dialog):
    def __init__(self, iface):
        QtWidgets.QDialog.__init__(self)
        self.iface = iface
        self.setupUi(self)


class Ui_csv2shp(QtWidgets.QDialog, Ui_csv2shp_Dialog):
    def __init__(self, iface):
        QtWidgets.QDialog.__init__(self)
        self.iface = iface
        self.setupUi(self)


class Ui_gpx2shp(QtWidgets.QDialog, Ui_gpx2shp_Dialog):
    def __init__(self, iface):
        QtWidgets.QDialog.__init__(self)
        self.iface = iface
        self.setupUi(self)


class Ui_exportSHP(QtWidgets.QDialog, Ui_exportSHP_Dialog):
    def __init__(self, iface):
        QtWidgets.QDialog.__init__(self)
        self.iface = iface
        self.setupUi(self)

class Ui_editPOLY(QtWidgets.QDialog, Ui_editPOLY_Dialog):
    def __init__(self, iface):             
        QtWidgets.QDialog.__init__(self)
        self.iface = iface
        self.setupUi(self)
  

class Ui_photogpx(QtWidgets.QDialog, Ui_photogpx_Dialog):
    def __init__(self, iface):             
        QtWidgets.QDialog.__init__(self)
        self.iface = iface
        self.setupUi(self)

class ImportPhotosDialog(QtWidgets.QDialog, Ui_photosImp_Dialog):
    
    def __init__(self, iface):             
        QtWidgets.QDialog.__init__(self)
        self.iface = iface 
        self.setupUi(self)

class Ui_IMGPairCSV(QtWidgets.QDialog, Ui_IMGPairCSV_Dialog):
    def __init__(self, iface):             
        QtWidgets.QDialog.__init__(self)
        self.iface = iface 
        self.setupUi(self)
        
class Ui_GPXrevise(QtWidgets.QDialog, Ui_GPXrevise_Dialog):
    
    def __init__(self, iface):             
        QtWidgets.QDialog.__init__(self)
        self.iface = iface 
        self.setupUi(self)

        

class Ui_wms(QtWidgets.QDialog, Ui_wms_Dialog):
    
    def __init__(self, iface):             
        QtWidgets.QDialog.__init__(self)
        self.iface = iface 
        self.setupUi(self)
        

# class Ui_positioning(QtWidgets.QDialog, Ui_positioning_Dialog):
    
#     def __init__(self, iface):             
#         QtWidgets.QDialog.__init__(self)
#         self.iface = iface 
#         self.setupUi(self)
       
class Ui_positioning(QtWidgets.QDialog, Ui_positioning_dia):
    
    def __init__(self, iface):             
        QtWidgets.QDialog.__init__(self)
        self.iface = iface 
        self.setupUi(self)

class Ui_cadastre(QtWidgets.QDialog, Ui_cadastre_Dialog):
    
    def __init__(self, iface):             
        QtWidgets.QDialog.__init__(self)
        self.iface = iface 
        self.setupUi(self) 

class Ui_infor(QtWidgets.QDialog, Ui_infor_Dialog):
    
    def __init__(self, iface):             
        QtWidgets.QDialog.__init__(self)
        self.iface = iface 
        self.setupUi(self)

class Ui_Ecological2shp(QtWidgets.QDialog, Ui_Ecological2shp_Dialog):
    
    def __init__(self, iface):             
        QtWidgets.QDialog.__init__(self)
        self.iface = iface 
        self.setupUi(self)
