# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\vincentlu\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tfb_tools3\photogpx.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_photogpx_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(399, 462)
        Dialog.setAcceptDrops(False)
        Dialog.setAutoFillBackground(False)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(140, 410, 91, 35))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 20, 361, 241))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(10, 70, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(90, 70, 221, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.toolButton = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton.setGeometry(QtCore.QRect(320, 70, 25, 25))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_3 = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton_3.setGeometry(QtCore.QRect(320, 30, 25, 25))
        self.toolButton_3.setObjectName("toolButton_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 30, 221, 25))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 120, 331, 101))
        self.groupBox_6.setObjectName("groupBox_6")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_8.setGeometry(QtCore.QRect(190, 30, 81, 20))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_9.setGeometry(QtCore.QRect(100, 30, 81, 20))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_10.setGeometry(QtCore.QRect(20, 30, 81, 20))
        self.radioButton_10.setChecked(True)
        self.radioButton_10.setObjectName("radioButton_10")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox.setGeometry(QtCore.QRect(20, 70, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_2.setGeometry(QtCore.QRect(100, 70, 42, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_3.setGeometry(QtCore.QRect(180, 70, 42, 22))
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_4.setGeometry(QtCore.QRect(250, 70, 42, 22))
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setGeometry(QtCore.QRect(70, 70, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(150, 70, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(230, 70, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(300, 70, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 280, 361, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox.setGeometry(QtCore.QRect(160, 70, 131, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 30, 221, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton_2.setGeometry(QtCore.QRect(330, 30, 25, 25))
        self.toolButton_2.setObjectName("toolButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "照片GPS軌跡定位"))
        self.pushButton.setText(_translate("Dialog", "開始轉換"))
        self.groupBox_4.setTitle(_translate("Dialog", "輸入"))
        self.label.setText(_translate("Dialog", "選取GPS軌跡"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "GPX檔路徑"))
        self.toolButton.setText(_translate("Dialog", "..."))
        self.toolButton_3.setText(_translate("Dialog", "..."))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "照片(.jpe)路徑"))
        self.label_4.setText(_translate("Dialog", "選取照片"))
        self.groupBox_6.setTitle(_translate("Dialog", "進階設定-調整照片拍照時間"))
        self.radioButton_8.setText(_translate("Dialog", "減少"))
        self.radioButton_9.setText(_translate("Dialog", "增加"))
        self.radioButton_10.setText(_translate("Dialog", "無"))
        self.label_5.setText(_translate("Dialog", "日"))
        self.label_6.setText(_translate("Dialog", "時"))
        self.label_7.setText(_translate("Dialog", "分"))
        self.label_8.setText(_translate("Dialog", "秒"))
        self.groupBox_5.setTitle(_translate("Dialog", "輸出"))
        self.comboBox.setItemText(0, _translate("Dialog", "WGS 84"))
        self.comboBox.setItemText(1, _translate("Dialog", "TWD 97"))
        self.label_3.setText(_translate("Dialog", "請選擇輸出檔案坐標系統"))
        self.label_2.setText(_translate("Dialog", "輸出檔案"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "檔案輸出路徑"))
        self.toolButton_2.setText(_translate("Dialog", "..."))


