# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\admin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\TFB-Tools3\positioning_dia_test.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel,
                             QComboBox, QGroupBox, QLineEdit, QPushButton, QTabWidget, QRadioButton)

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)


class Ui_positioning_dia_test(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(535, 864)
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 341, 101))
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(70, 30, 131, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(210, 30, 121, 25))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(70, 60, 131, 25))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label = QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 170, 341, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_6 = QComboBox(self.groupBox_2)
        self.comboBox_6.setEnabled(False)
        self.comboBox_6.setGeometry(QtCore.QRect(210, 20, 121, 25))
        self.comboBox_6.setObjectName("comboBox_6")
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox_7 = QComboBox(self.groupBox_2)
        self.comboBox_7.setEnabled(False)
        self.comboBox_7.setGeometry(QtCore.QRect(70, 50, 151, 25))
        self.comboBox_7.setObjectName("comboBox_7")
        self.label_5 = QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_8 = QComboBox(self.groupBox_2)
        self.comboBox_8.setEnabled(False)
        self.comboBox_8.setGeometry(QtCore.QRect(70, 80, 131, 25))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_9 = QComboBox(self.groupBox_2)
        self.comboBox_9.setEnabled(False)
        self.comboBox_9.setGeometry(QtCore.QRect(210, 80, 121, 25))
        self.comboBox_9.setObjectName("comboBox_9")
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_17 = QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(10, 110, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEdit = QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(70, 110, 131, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 110, 75, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_5 = QComboBox(self.groupBox_2)
        self.comboBox_5.setGeometry(QtCore.QRect(70, 20, 131, 25))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.groupBox_3 = QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 340, 341, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_7 = QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox_10 = QComboBox(self.groupBox_3)
        self.comboBox_10.setGeometry(QtCore.QRect(170, 30, 161, 25))
        self.comboBox_10.setEditable(True)
        self.comboBox_10.setObjectName("comboBox_10")
        self.label_8 = QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.comboBox_11 = QComboBox(self.groupBox_3)
        self.comboBox_11.setGeometry(QtCore.QRect(110, 60, 221, 25))
        self.comboBox_11.setEditable(True)
        self.comboBox_11.setObjectName("comboBox_11")
        self.label_9 = QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comboBox_12 = QComboBox(self.groupBox_3)
        self.comboBox_12.setGeometry(QtCore.QRect(110, 90, 221, 25))
        self.comboBox_12.setEditable(True)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_28 = CustomComboBox(self.groupBox_3)
        self.comboBox_28.setGeometry(QtCore.QRect(80, 30, 81, 25))
        self.comboBox_28.setObjectName("comboBox_28")
        self.comboBox_28.addItem("")
        self.comboBox_19 = QComboBox(Dialog)
        self.comboBox_19.setGeometry(QtCore.QRect(20, 20, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_19.setFont(font)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 480, 501, 231))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_4 = QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 471, 191))
        self.groupBox_4.setObjectName("groupBox_4")
        self.comboBox_14 = CustomComboBox(self.groupBox_4)
        self.comboBox_14.setGeometry(QtCore.QRect(230, 110, 221, 25))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.label_11 = QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_13 = QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.comboBox_16 = CustomComboBox(self.groupBox_4)
        self.comboBox_16.setGeometry(QtCore.QRect(170, 20, 281, 25))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.label_14 = QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.comboBox_17 = CustomComboBox(self.groupBox_4)
        self.comboBox_17.setGeometry(QtCore.QRect(170, 50, 281, 25))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.label_15 = QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(10, 80, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.comboBox_18 = CustomComboBox(self.groupBox_4)
        self.comboBox_18.setGeometry(QtCore.QRect(190, 80, 261, 25))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.label_16 = QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(10, 140, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.comboBox_20 = CustomComboBox(self.groupBox_4)
        self.comboBox_20.setGeometry(QtCore.QRect(160, 140, 291, 25))
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_21 = CustomComboBox(self.groupBox_4)
        self.comboBox_21.setGeometry(QtCore.QRect(80, 50, 81, 25))
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.comboBox_22 = CustomComboBox(self.groupBox_4)
        self.comboBox_22.setGeometry(QtCore.QRect(100, 80, 81, 25))
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.addItem("")
        self.comboBox_23 = CustomComboBox(self.groupBox_4)
        self.comboBox_23.setGeometry(QtCore.QRect(140, 110, 81, 25))
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.addItem("")
        self.comboBox_24 = CustomComboBox(self.groupBox_4)
        self.comboBox_24.setGeometry(QtCore.QRect(70, 140, 81, 25))
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_24.addItem("")
        self.comboBox_29 = CustomComboBox(self.groupBox_4)
        self.comboBox_29.setGeometry(QtCore.QRect(80, 20, 81, 25))
        self.comboBox_29.setObjectName("comboBox_29")
        self.comboBox_29.addItem("")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_4 = QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(330, 330, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(100, 330, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QPushButton(self.tab_3)
        self.pushButton_6.setGeometry(QtCore.QRect(14, 330, 81, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox_5 = QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 471, 191))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_12 = QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(10, 80, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_10 = QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.comboBox_13 = CustomComboBox(self.groupBox_5)
        self.comboBox_13.setGeometry(QtCore.QRect(180, 50, 281, 25))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_15 = CustomComboBox(self.groupBox_5)
        self.comboBox_15.setGeometry(QtCore.QRect(180, 80, 281, 25))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.label_3 = QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_4 = CustomComboBox(self.groupBox_5)
        self.comboBox_4.setGeometry(QtCore.QRect(180, 20, 281, 25))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_25 = CustomComboBox(self.groupBox_5)
        self.comboBox_25.setGeometry(QtCore.QRect(90, 20, 81, 25))
        self.comboBox_25.setObjectName("comboBox_25")
        self.comboBox_25.addItem("")
        self.comboBox_26 = CustomComboBox(self.groupBox_5)
        self.comboBox_26.setGeometry(QtCore.QRect(90, 50, 81, 25))
        self.comboBox_26.setObjectName("comboBox_26")
        self.comboBox_26.addItem("")
        self.comboBox_27 = CustomComboBox(self.groupBox_5)
        self.comboBox_27.setGeometry(QtCore.QRect(90, 80, 81, 25))
        self.comboBox_27.setObjectName("comboBox_27")
        self.comboBox_27.addItem("")
        self.tabWidget.addTab(self.tab_3, "")
        self.groupBox_6 = QGroupBox(Dialog)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 730, 351, 121))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_21 = QLabel(self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(10, 50, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lineEdit_2 = QLineEdit(self.groupBox_6)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 50, 131, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_24 = QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(180, 50, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.lineEdit_3 = QLineEdit(self.groupBox_6)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 50, 131, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_3 = QPushButton(self.groupBox_6)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 80, 75, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.radioButton = QRadioButton(self.groupBox_6)
        self.radioButton.setGeometry(QtCore.QRect(30, 20, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QRadioButton(self.groupBox_6)
        self.radioButton_2.setGeometry(QtCore.QRect(100, 20, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "林務局圖資操作工具"))
        self.groupBox.setTitle(_translate("Dialog", "轄管範圍定位"))
        self.label.setText(_translate("Dialog", "事業區"))
        self.label_2.setText(_translate("Dialog", "林班"))
        self.groupBox_2.setTitle(_translate("Dialog", "國有林地籍圖定位"))
        self.label_4.setText(_translate("Dialog", "縣市"))
        self.label_5.setText(_translate("Dialog", "事務所"))
        self.label_6.setText(_translate("Dialog", "段"))
        self.label_17.setText(_translate("Dialog", "地號"))
        self.pushButton_2.setText(_translate("Dialog", "查詢"))
        self.comboBox_5.setCurrentText(_translate("Dialog", "請選擇縣市"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "請選擇縣市"))
        self.groupBox_3.setTitle(_translate("Dialog", "保安林定位"))
        self.label_7.setText(_translate("Dialog", "保安林編號"))
        self.label_8.setText(_translate("Dialog", "段號"))
        self.label_9.setText(_translate("Dialog", "地號 - 母號"))
        self.comboBox_28.setCurrentText(_translate("Dialog", "選擇欄位"))
        self.comboBox_28.setItemText(0, _translate("Dialog", "選擇欄位"))
        self.comboBox_19.setItemText(0, _translate("Dialog", "請選擇欲定位類別"))
        self.comboBox_19.setItemText(1, _translate("Dialog", "轄管範圍定位"))
        self.comboBox_19.setItemText(2, _translate("Dialog", "保安林定位"))
        self.comboBox_19.setItemText(3, _translate("Dialog", "保護區與育樂園區定位"))
        self.comboBox_19.setItemText(4, _translate("Dialog", "GoToXY"))
        self.groupBox_4.setTitle(_translate("Dialog", "保護區定位"))
        self.comboBox_14.setItemText(0, _translate("Dialog", "請選擇欲定位區位"))
        self.label_11.setText(_translate("Dialog", "野生動物重要棲息環境"))
        self.label_13.setText(_translate("Dialog", "自然保護區"))
        self.comboBox_16.setItemText(0, _translate("Dialog", "請選擇欲定位區位"))
        self.label_14.setText(_translate("Dialog", "自然保留區"))
        self.comboBox_17.setItemText(0, _translate("Dialog", "請選擇欲定位區位"))
        self.label_15.setText(_translate("Dialog", "野生動物保護區"))
        self.comboBox_18.setItemText(0, _translate("Dialog", "請選擇欲定位區位"))
        self.label_16.setText(_translate("Dialog", "國家公園"))
        self.comboBox_20.setItemText(0, _translate("Dialog", "請選擇欲定位區位"))
        self.comboBox_21.setCurrentText(_translate("Dialog", "選擇欄位"))
        self.comboBox_21.setItemText(0, _translate("Dialog", "選擇欄位"))
        self.comboBox_22.setCurrentText(_translate("Dialog", "選擇欄位"))
        self.comboBox_22.setItemText(0, _translate("Dialog", "選擇欄位"))
        self.comboBox_23.setCurrentText(_translate("Dialog", "選擇欄位"))
        self.comboBox_23.setItemText(0, _translate("Dialog", "選擇欄位"))
        self.comboBox_24.setCurrentText(_translate("Dialog", "選擇欄位"))
        self.comboBox_24.setItemText(0, _translate("Dialog", "選擇欄位"))
        self.comboBox_29.setItemText(0, _translate("Dialog", "選擇欄位"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "保護區"))
        self.pushButton_4.setText(_translate("Dialog", "套疊圖層"))
        self.pushButton_5.setText(_translate("Dialog", "儲存列表"))
        self.pushButton_6.setText(_translate("Dialog", "從列表移除"))
        self.groupBox_5.setTitle(_translate("Dialog", "育樂園區定位"))
        self.label_12.setText(_translate("Dialog", "林業文化園區"))
        self.label_10.setText(_translate("Dialog", "平地森林園區"))
        self.comboBox_13.setItemText(0, _translate("Dialog", "請選擇欲定位區位"))
        self.comboBox_15.setItemText(0, _translate("Dialog", "請選擇欲定位區位"))
        self.label_3.setText(_translate("Dialog", "森林遊樂區"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "請選擇欲定位區位"))
        self.comboBox_25.setCurrentText(_translate("Dialog", "選擇欄位"))
        self.comboBox_25.setItemText(0, _translate("Dialog", "選擇欄位"))
        self.comboBox_26.setCurrentText(_translate("Dialog", "選擇欄位"))
        self.comboBox_26.setItemText(0, _translate("Dialog", "選擇欄位"))
        self.comboBox_27.setCurrentText(_translate("Dialog", "選擇欄位"))
        self.comboBox_27.setItemText(0, _translate("Dialog", "選擇欄位"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "育樂區"))
        self.groupBox_6.setTitle(_translate("Dialog", "GoToXY"))
        self.label_21.setText(_translate("Dialog", "X:"))
        self.label_24.setText(_translate("Dialog", "Y:"))
        self.pushButton_3.setText(_translate("Dialog", "定位"))
        self.radioButton.setText(_translate("Dialog", "TWD97"))
        self.radioButton_2.setText(_translate("Dialog", "WGS84"))

class CustomComboBox(QComboBox):
    popupAboutToBeShown = QtCore.pyqtSignal()

    def __init__(self, parent=None):
        super(CustomComboBox, self).__init__(parent)

    def showPopup(self):
        self.popupAboutToBeShown.emit()
        QComboBox.showPopup(self)
